use anyhow::Result;
use std::sync::Arc;
use std::process::Command;
use crate::database::Database;

pub struct NginxController {
    database: Arc<Database>,
}

impl NginxController {
    pub fn new(database: Arc<Database>) -> Self {
        Self { database }
    }

    pub async fn take_control(&self) -> Result<()> {
        // We completely control nginx
        self.wipe_and_recreate_config().await?;
        Ok(())
    }

    async fn wipe_and_recreate_config(&self) -> Result<()> {
        // Create directories
        std::fs::create_dir_all("/etc/nginx/vhosts.d")?;

        // Generate nginx.conf from database
        let config = self.generate_nginx_conf().await?;
        std::fs::write("/etc/nginx/nginx.conf", config)?;

        // Download latest mime.types
        let mime_types = self.download_mime_types().await?;
        std::fs::write("/etc/nginx/mime.types", mime_types)?;

        // Test configuration
        let output = Command::new("nginx")
            .args(&["-t"])
            .output()?;

        if !output.status.success() {
            return Err(anyhow::anyhow!("nginx configuration test failed"));
        }

        Ok(())
    }

    async fn generate_nginx_conf(&self) -> Result<String> {
        let user = self.get_nginx_user()?;
        let workers = self.database.get_config("nginx.workers").await?;
        let connections = self.database.get_config("nginx.connections").await?;

        let workers = if workers.is_empty() { "auto".to_string() } else { workers };
        let connections = if connections.is_empty() { "1024".to_string() } else { connections };

        Ok(format!(r#"# Generated by CasVPS - DO NOT EDIT
user {};
worker_processes {};
pid /run/nginx.pid;

events {{
    worker_connections {};
    use epoll;
    multi_accept on;
}}

http {{
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/xml text/javascript application/json application/javascript application/xml+rss application/rss+xml application/atom+xml image/svg+xml text/javascript application/x-javascript application/x-font-ttf application/vnd.ms-fontobject font/opentype;

    include /etc/nginx/vhosts.d/*.conf;
}}"#, user, workers, connections))
    }

    fn get_nginx_user(&self) -> Result<String> {
        // Detect distro and return appropriate user
        if std::path::Path::new("/etc/debian_version").exists() {
            Ok("www-data".to_string())
        } else if std::path::Path::new("/etc/redhat-release").exists() {
            Ok("nginx".to_string())
        } else {
            Ok("nginx".to_string())
        }
    }

    async fn download_mime_types(&self) -> Result<String> {
        // For now, return a basic mime.types
        Ok(include_str!("../../assets/mime.types").to_string())
    }
}