use anyhow::Result;
use std::sync::Arc;
use crate::database::Database;

pub struct PostfixController {
    database: Arc<Database>,
}

impl PostfixController {
    pub fn new(database: Arc<Database>) -> Self {
        Self { database }
    }

    pub async fn take_control(&self) -> Result<()> {
        // We completely control postfix
        self.create_required_files().await?;
        self.create_queue_dirs()?;
        Ok(())
    }

    async fn create_required_files(&self) -> Result<()> {
        // Create main.cf
        let main_cf = self.generate_main_cf().await?;
        std::fs::write("/etc/postfix/main.cf", main_cf)?;

        // Create master.cf
        let master_cf = self.generate_master_cf();
        std::fs::write("/etc/postfix/master.cf", master_cf)?;

        // Create postfix-files
        let postfix_files = self.generate_postfix_files();
        std::fs::write("/etc/postfix/postfix-files", postfix_files)?;

        // Create aliases
        std::fs::write("/etc/aliases", "postmaster: root\nroot: admin@localhost\n")?;

        Ok(())
    }

    async fn generate_main_cf(&self) -> Result<String> {
        Ok(r#"# Generated by CasVPS - DO NOT EDIT
queue_directory = /var/spool/postfix
command_directory = /usr/sbin
daemon_directory = /usr/libexec/postfix
data_directory = /var/lib/postfix
mail_owner = postfix
inet_interfaces = localhost
inet_protocols = ipv4
mydestination = $myhostname, localhost.$mydomain, localhost
unknown_local_recipient_reject_code = 550
relayhost =
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases"#.to_string())
    }

    fn generate_master_cf(&self) -> String {
        r#"# Generated by CasVPS - DO NOT EDIT
# ==========================================================================
# service type  private unpriv  chroot  wakeup  maxproc command + args
# ==========================================================================
smtp      inet  n       -       y       -       -       smtpd
pickup    unix  n       -       y       60      1       pickup
cleanup   unix  n       -       y       -       0       cleanup
qmgr      unix  n       -       n       300     1       qmgr
tlsmgr    unix  -       -       y       1000?   1       tlsmgr
rewrite   unix  -       -       y       -       -       trivial-rewrite
bounce    unix  -       -       y       -       0       bounce
defer     unix  -       -       y       -       0       bounce
trace     unix  -       -       y       -       0       bounce
verify    unix  -       -       y       -       1       verify
flush     unix  n       -       y       1000?   0       flush
proxymap  unix  -       -       n       -       -       proxymap
proxywrite unix -       -       n       -       1       proxymap
smtp      unix  -       -       y       -       -       smtp
relay     unix  -       -       y       -       -       smtp
showq     unix  n       -       y       -       -       showq
error     unix  -       -       y       -       -       error
retry     unix  -       -       y       -       -       error
discard   unix  -       -       y       -       -       discard
local     unix  -       n       n       -       -       local
virtual   unix  -       n       n       -       -       virtual
lmtp      unix  -       -       y       -       -       lmtp
anvil     unix  -       -       y       -       1       anvil
scache    unix  -       -       y       -       1       scache"#.to_string()
    }

    fn generate_postfix_files(&self) -> String {
        r#"# Generated by CasVPS - DO NOT EDIT
$queue_directory/active:d:$mail_owner:-:700
$queue_directory/bounce:d:$mail_owner:-:700
$queue_directory/corrupt:d:$mail_owner:-:700
$queue_directory/defer:d:$mail_owner:-:700
$queue_directory/deferred:d:$mail_owner:-:700
$queue_directory/flush:d:$mail_owner:-:700
$queue_directory/hold:d:$mail_owner:-:700
$queue_directory/incoming:d:$mail_owner:-:700
$queue_directory/saved:d:$mail_owner:-:700
$queue_directory/trace:d:$mail_owner:-:700
$queue_directory/maildrop:d:$mail_owner:postdrop:730
$queue_directory/public:d:$mail_owner:-:710
$queue_directory/private:d:$mail_owner:-:700
$queue_directory/pid:d:root:-:755"#.to_string()
    }

    fn create_queue_dirs(&self) -> Result<()> {
        use std::os::unix::fs::PermissionsExt;

        let queue_dirs = vec![
            ("/var/spool/postfix", "postfix", "root", 0o755),
            ("/var/spool/postfix/active", "postfix", "root", 0o700),
            ("/var/spool/postfix/bounce", "postfix", "root", 0o700),
            ("/var/spool/postfix/corrupt", "postfix", "root", 0o700),
            ("/var/spool/postfix/defer", "postfix", "root", 0o700),
            ("/var/spool/postfix/deferred", "postfix", "root", 0o700),
            ("/var/spool/postfix/flush", "postfix", "root", 0o700),
            ("/var/spool/postfix/hold", "postfix", "root", 0o700),
            ("/var/spool/postfix/incoming", "postfix", "root", 0o700),
            ("/var/spool/postfix/maildrop", "postfix", "postdrop", 0o730),
            ("/var/spool/postfix/pid", "root", "root", 0o755),
            ("/var/spool/postfix/private", "postfix", "root", 0o700),
            ("/var/spool/postfix/public", "postfix", "root", 0o710),
            ("/var/spool/postfix/saved", "postfix", "root", 0o700),
            ("/var/spool/postfix/trace", "postfix", "root", 0o700),
        ];

        for (path, _user, _group, mode) in queue_dirs {
            std::fs::create_dir_all(path)?;
            let metadata = std::fs::metadata(path)?;
            let mut perms = metadata.permissions();
            perms.set_mode(mode);
            std::fs::set_permissions(path, perms)?;
        }

        Ok(())
    }
}